### ISSUE TITLE
Set up front end pages for multiple pools

### ISSUE THREAD

**Issue by suprabhatgurrala** [suprabhatgurrala/nba-wins-pool#20]
Currently in #14 the homepage is hardcoded to show `sg` pool, even though backend supports other ones.

Frontend needs to be updated to support going to `/<pool_slug>/leaderboard` or similar path to load a specific pool

**Comment by ejnarvala** [comment]
Went with this routing to start: 

`/:poolId` (e.g. `/sg` or `/kk`)

made `/` redirect to `/sg`

https://github.com/suprabhatgurrala/nba-wins-pool/pull/26
